builders:
  slang_i18n_generator:
    import: "package:slang_i18n_generator/slang_i18n_generator.dart"
    builder_factories: ["slangI18nGeneratorFactory"]
    build_extensions: {".slang.json": [".i18n.json"]}
    auto_apply: dependents
    build_to: source
targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
      slang_i18n_generator:
        options:
          additional_locales:
            - jp
